### ISSUE TITLE
Values of the messages are not displaying, just the keys

### ISSUE THREAD

**Issue by Apoerin** [stevensacks/storybook-react-intl#5] opened 2021-12-01 09:14 UTC
I set up the addon configuration as it was written in the guide https://storybook.js.org/addons/storybook-react-intl
But the problem is in the following - I don't see values of messages keys, just keys themselves.

_package.json_
```
"react-intl": "^2.8.0",
"storybook-react-intl": "^0.9.2"
```
_reactIntl.js_
```
import { addLocaleData } from 'react-intl';
import enLocaleData from 'react-intl/locale-data/en';
import deLocaleData from 'react-intl/locale-data/de';

addLocaleData(enLocaleData);
addLocaleData(deLocaleData);

const locales = ['en', 'de'];

const messages = locales.reduce((acc, lang) => ({
  ...acc,
  [lang]: require(`../src/messages/${lang}.json`), // whatever the relative path to your messages json is
}), {});

export const reactIntl = {
  defaultLocale: 'en',
  locales,
  messages,
};
```
_main.js_
```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app",
    "storybook-addon-material-ui",
    "storybook-react-intl",
  ],
  "framework": "@storybook/react"
}
```
_preview.js_
```
import React from 'react';

import { addDecorator, configure } from '@storybook/react';
import { Provider } from 'react-redux';
import configureStore from '../src/configureStore';

import { IntlProvider } from 'react-intl';

import {reactIntl} from './reactIntl.js';

// Global Redux/Intl Provider
const store = configureStore()

const withProvider = (story) => (
  <Provider store={store}>
    <IntlProvider>
      {story()}
    </IntlProvider>
  </Provider>
);

addDecorator(withProvider);


export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  reactIntl,
  locale: reactIntl.defaultLocale,
  locales: {
    en: 'English',
    de: 'Deutsche',
  },
  docs: {
    // opt-out of inline rendering
    inlineStories: false,
  },
}
```
So my components have the following structure for messages: 
`<FormattedMessage id="account.tokens.button.cancel" />`
`"account.tokens.button.cancel": "Cancel",`

I expect to see on rendered `Button`  just a word `Cancel`, but instead, I see the whole id for that word `account.tokens.button.cancel`.
Am I missing something or how to make that work?

**Comment by Apoerin** [comment] 2021-12-15 08:39
@stevensacks any idea how to fix it?

**Comment by stevensacks** [comment] 2021-12-22 07:44
I just released a new version updated for Storybook 6.4 that also has updated instructions in the README for how to use this addon. I’ve tested and it is working for me. 

Please try using it as described in the updated README. For example, this addons wraps your stories with the IntlProvider for you. You should not be doing it yourself.

**Comment by Apoerin** [comment] 2021-12-23 10:17
Yes, I understand, but without wrapping with IntlProvider by myself it gives me 
`[React Intl] Could not find required 'intl' object. <IntlProvider> needs to exist in the component ancestry.` and I have it provided in my `App.js`

**Comment by stevensacks** [comment] 2021-12-23 13:22
This addon wraps all stories inside IntlProvider. It won’t work if you have a story which renders a component that has its own IntlProvider.

https://github.com/stevensacks/storybook-react-intl/blob/main/src/withReactIntl.tsx

**Comment by w01fgang** [comment] 2021-12-23 17:18
I have the same error `[React Intl] Could not find required 'intl' object. <IntlProvider> needs to exist in the component ancestry.` Did everything as described in docs.

-- Edit

Fixed it by running `npx install-peerdeps --dev storybook-react-intl`

It seems that some peer dependency was missing.

**Comment by stevensacks** [comment] 2021-12-24 00:33
You should have seen warnings in the console when installing this plugin about those peer dependencies, however, I will update the installation instructions to include the peer dependencies (which, besides the obvious one, react-intl, are official storybook ones).

Just to be clear, this is an addon for Storybook to support react-intl. It is not react-intl itself and intentionally does not include it since you will have already included it in your actual project.

**Comment by stevensacks** [comment] 2021-12-24 00:44
Hm. I will look into this more closely and figure out which peer dependencies are to blame.

**Comment by stevensacks** [comment] 2021-12-24 08:48
I believe I have solved this issue in the latest release 1.0.3. Please try it. You might want to `rm -rf node_modules` and then either `npm i` or `yarn` (depending on your package manager) just to make sure.

**Comment by w01fgang** [comment] 2021-12-24 12:55
Confirm. The latest version doesn't have this error anymore.
Thanks!

**Comment by Apoerin** [comment] 2021-12-24 12:58
no error, but the problem with displaying still remains

**Comment by w01fgang** [comment] 2021-12-24 13:01
@Apoerin did you remove your custom `IntlProvider`?

**Comment by Apoerin** [comment] 2021-12-24 13:33
@w01fgang yes, just `IntlProvider` in my project left ( not in storybook)

**Comment by w01fgang** [comment] 2021-12-24 14:49
@Apoerin could you share a repo with minimal code with reproduced error?

**Comment by Apoerin** [comment] 2021-12-24 14:58
@w01fgang Installed and set up **just as described in README**
`[React Intl] Missing message: "login.dialog.title" for locale: "en"`


`Login.stories.js`
```
import React from 'react';
import { storiesOf } from '@storybook/react';

import Login from '../../components/login/index';
import SmsVerificationDialog from '../../components/login/smsVerification/SmsVerificationDialog';

export default {
 title: 'Login/Login',
 component: Login,
};

storiesOf('Login/Login', module)
  .add('Login Page', () => (
    <Login />
  ))
  .add('Sms Verification Dialog', () => (
    <SmsVerificationDialog open={true} />
  ))
```
And when the story renders I see `login.dialog.title` instead of `Log in`

**Comment by w01fgang** [comment] 2021-12-24 15:38
@Apoerin my `preview.js` looks a bit different:
1. I don't use `addDecorator` and instead I export `decorators` array
2. I don't call `story` function and instead render it as a component providing context.

```javascript
import { reactIntl } from './reactIntl';

const withStoreProvider = (Story, context) => {

  return (
    <Provider store={store}>
      <Story {...context} />
    </Provider>
  );
};

export const decorators = [withStoreProvider];

export const parameters = {
  reactIntl,
  locale: reactIntl.defaultLocale,
  locales: reactIntl.locales.reduce(
    (locales, locale) => ({ ...locales, [locale]: locale.toUpperCase() }),
    {}
  )
};
```
Can you console.log context and find your messages inside? Do you have a message for `login.dialog.title` inside?

**Comment by Apoerin** [comment] 2021-12-24 16:41
@w01fgang yes, I see all messages in console.log

**Comment by Apoerin** [comment] 2021-12-24 17:04
Also upgrading to latest version of Storybook `6.4.9` gives me runtime error, loading and

`Uncaught SyntaxError: Unexpected token ':' vendors~main.iframe.bundle.js:81304` 

and I can't reproduce this one neither as the project is huge. So I'm using Storybook `6.3.12`

**Comment by stevensacks** [comment] 2021-12-27 04:22
This addon is built to work with the latest version of Storybook (6.4.x as of this writing).

I noticed in your example that you’re using an outdated and deprecated method of writing stories (storiesOf, for example). It’s possible that there are unforeseen conflicts between those old no longer supported ways of writing stories and addons written for Storybook 6.4.

I have tested this addon in isolation and in a large real world project and it works without any issues when used as described in the README file.

It might be worth looking into updating your storybook stories to use the modern style of story writing. I believe they have code mod scripts that can automate many of the changes required.

As an aside, I recommend using `storyFn()` instead of the `<Story/>` component, as I have seen that component misbehave with certain addons.

At this point, I don’t think there’s much else I can do. I’ve resolved the peer dependency issue. I’ll continue to keep this addon updated to the latest versions of React Intl and Storybook.

That said, you are welcome to fork this repo and dig through [what little source code there is](https://github.com/stevensacks/storybook-react-intl/blob/main/src/withReactIntl.tsx) to try and resolve your issue. If you’re able to find a solution, make a PR and I’ll reopen this issue and review your PR.

You can also follow the [Storybook Addon Guide](https://storybook.js.org/blog/create-storybook-addon/) to build your own React Intl addon. They have a [step by step tutorial](https://storybook.js.org/docs/react/addons/writing-addons), as well.

For now, though, I’m going to close this issue.

**Closed as completed** 2021-12-27 04:27 UTC
